"""Type stubs for the nanobind C extension."""

from collections.abc import Callable
from typing import Final

ERR_SUCCESS: Final[int]
ERR_INVALID: Final[int]
ERR_FAILURE: Final[int]
ERR_NOT_AVAIL: Final[int]
ERR_TOO_SMALL: Final[int]

def preload() -> None: ...
def cleanup() -> None: ...
def init_logger(level: int, callback: Callable[[int, str], None] | None) -> None: ...
def set_thread_pool_size(count: int) -> int: ...

class PeerConnection:
    def __init__(
        self,
        ice_servers: list[str],
        port_range_begin: int = ...,
        port_range_end: int = ...,
        mtu: int = ...,
        max_message_size: int = ...,
        enable_ice_tcp: bool = ...,
        disable_auto_negotiation: bool = ...,
        certificate_type: int = ...,
        ice_transport_policy: int = ...,
    ) -> None: ...
    @property
    def handle(self) -> int: ...
    def close(self) -> None: ...
    def destroy(self) -> None: ...
    def create_data_channel(
        self,
        label: str,
        unordered: bool = ...,
        unreliable: bool = ...,
        max_packet_lifetime: int = ...,
        max_retransmits: int = ...,
        protocol: str = ...,
        negotiated: bool = ...,
        manual_stream: bool = ...,
        stream: int = ...,
    ) -> int: ...
    def set_local_description(self, type: str | None = ...) -> None: ...
    def set_remote_description(self, sdp: str, type: str) -> None: ...
    def add_remote_candidate(self, candidate: str, mid: str = ...) -> None: ...
    def get_local_description(self) -> str | None: ...
    def get_remote_description(self) -> str | None: ...
    def get_local_description_type(self) -> str | None: ...
    def set_on_local_description(self, callback: Callable[[str, str], None]) -> None: ...
    def set_on_local_candidate(self, callback: Callable[[str, str], None]) -> None: ...
    def set_on_state_change(self, callback: Callable[[int], None]) -> None: ...
    def set_on_ice_state_change(self, callback: Callable[[int], None]) -> None: ...
    def set_on_gathering_state_change(self, callback: Callable[[int], None]) -> None: ...
    def set_on_signaling_state_change(self, callback: Callable[[int], None]) -> None: ...
    def set_on_data_channel(self, callback: Callable[[int], None]) -> None: ...

class DataChannel:
    def __init__(self, handle: int) -> None: ...
    @property
    def handle(self) -> int: ...
    def send_bytes(self, data: bytes) -> None: ...
    def send_text(self, data: str) -> None: ...
    def is_open(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def buffered_amount(self) -> int: ...
    def max_message_size(self) -> int: ...
    def set_buffered_amount_low_threshold(self, amount: int) -> None: ...
    def label(self) -> str | None: ...
    def protocol(self) -> str | None: ...
    def stream(self) -> int: ...
    def close(self) -> None: ...
    def destroy(self) -> None: ...
    def set_on_open(self, callback: Callable[[], None]) -> None: ...
    def set_on_closed(self, callback: Callable[[], None]) -> None: ...
    def set_on_error(self, callback: Callable[[str], None]) -> None: ...
    def set_on_message(self, callback: Callable[[bytes | str], None]) -> None: ...
    def set_on_buffered_amount_low(self, callback: Callable[[], None]) -> None: ...
